//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BD.WTTS.Client.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BD.WTTS.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 关于 的本地化字符串。
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}（原名 {1}） 的本地化字符串。
        /// </summary>
        public static string About_FormerName__ {
            get {
                return ResourceManager.GetString("About_FormerName__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 版本 {0} 的本地化字符串。
        /// </summary>
        public static string About_Version_ {
            get {
                return ResourceManager.GetString("About_Version_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该操作不是还原当前修改，而是使所有成就和统计数据归零。
        ///真的确定吗? 的本地化字符串。
        /// <summary>
        ///   查找类似 错误代码：{0}
        ///检索成就统计信息时出错，可能是该游戏没有成就，或者你没有该游戏。 的本地化字符串。
        /// <summary>
        ///   查找类似 新增 的本地化字符串。
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加平台 的本地化字符串。
        /// </summary>
        public static string AddPlatform {
            get {
                return ResourceManager.GetString("AddPlatform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 同意 的本地化字符串。
        /// </summary>
        public static string Agree {
            get {
                return ResourceManager.GetString("Agree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 和 的本地化字符串。
        /// </summary>
        public static string And {
            get {
                return ResourceManager.GetString("And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动参数 的本地化字符串。
        /// </summary>
        public static string Arguments {
            get {
                return ResourceManager.GetString("Arguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 返回 的本地化字符串。
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 背景 的本地化字符串。
        /// </summary>
        public static string Background {
            get {
                return ResourceManager.GetString("Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 绑定 的本地化字符串。
        /// </summary>
        public static string Bind {
            get {
                return ResourceManager.GetString("Bind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bug 提交 的本地化字符串。
        /// </summary>
        public static string BugReport {
            get {
                return ResourceManager.GetString("BugReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全部取消 的本地化字符串。
        /// </summary>
        public static string CancelAll {
            get {
                return ResourceManager.GetString("CancelAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新日志 的本地化字符串。
        /// </summary>
        public static string Changelog {
            get {
                return ResourceManager.GetString("Changelog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检查更新 的本地化字符串。
        /// </summary>
        public static string CheckUpdate {
            get {
                return ResourceManager.GetString("CheckUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭 的本地化字符串。
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 云同步 的本地化字符串。
        /// </summary>
        public static string CloudSync {
            get {
                return ResourceManager.GetString("CloudSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 网络加速 的本地化字符串。
        /// </summary>
        public static string CommunityFix {
            get {
                return ResourceManager.GetString("CommunityFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有启用任何加速项！！ 的本地化字符串。
        /// </summary>
        public static string CommunityFix_AccEmpty {
            get {
                return ResourceManager.GetString("CommunityFix_AccEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动时自动开启加速 的本地化字符串。
        /// </summary>
        public static string CommunityFix_AutoRunProxy {
            get {
                return ResourceManager.GetString("CommunityFix_AutoRunProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自定义 DoH 地址 的本地化字符串。
        /// </summary>
        public static string CommunityFix_CustomDohAddres {
            get {
                return ResourceManager.GetString("CommunityFix_CustomDohAddres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 移除证书 的本地化字符串。
        /// </summary>
        public static string CommunityFix_DeleteCertificate {
            get {
                return ResourceManager.GetString("CommunityFix_DeleteCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 CA 证书失败 的本地化字符串。
        /// </summary>
        public static string CommunityFix_DeleteCertificate_Fail {
            get {
                return ResourceManager.GetString("CommunityFix_DeleteCertificate_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 CA 证书成功 的本地化字符串。
        /// </summary>
        public static string CommunityFix_DeleteCertificate_Success {
            get {
                return ResourceManager.GetString("CommunityFix_DeleteCertificate_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DNS 解析遇到异常，请尝试在代理设置中修改其它 DNS 再次尝试 的本地化字符串。
        /// </summary>
        public static string CommunityFix_DNSErrorNotify {
            get {
                return ResourceManager.GetString("CommunityFix_DNSErrorNotify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑 Hosts 文件 的本地化字符串。
        /// </summary>
        public static string CommunityFix_EditHostsFile {
            get {
                return ResourceManager.GetString("CommunityFix_EditHostsFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启用 Http 协议转发到 Https (需监听 80 端口) 的本地化字符串。
        /// </summary>
        public static string CommunityFix_EnableHttpProxyToHttps {
            get {
                return ResourceManager.GetString("CommunityFix_EnableHttpProxyToHttps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启用 DoH 的本地化字符串。
        /// </summary>
        public static string CommunityFix_EnableUseDoh {
            get {
                return ResourceManager.GetString("CommunityFix_EnableUseDoh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 流量统计 的本地化字符串。
        /// </summary>
        public static string CommunityFix_FlowStatistics {
            get {
                return ResourceManager.GetString("CommunityFix_FlowStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mark 出现多个 [{0}]，请尝试重置 Hosts 文件或编辑 Hosts 文件并删除多余的 Mark 后再试一次 的本地化字符串。
        /// </summary>
        public static string CommunityFix_Hosts_MarkDuplicate_ {
            get {
                return ResourceManager.GetString("CommunityFix_Hosts_MarkDuplicate_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取加速信息失败，请检查程序是否能正常联网 的本地化字符串。
        /// </summary>
        public static string CommunityFix_ItemsEmpty {
            get {
                return ResourceManager.GetString("CommunityFix_ItemsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加速设置 的本地化字符串。
        /// </summary>
        public static string CommunityFix_MenuName {
            get {
                return ResourceManager.GetString("CommunityFix_MenuName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动网络加速失败 的本地化字符串。
        /// </summary>
        public static string CommunityFix_OnRunCatch {
            get {
                return ResourceManager.GetString("CommunityFix_OnRunCatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开证书文件夹 的本地化字符串。
        /// </summary>
        public static string CommunityFix_OpenCertificateDir {
            get {
                return ResourceManager.GetString("CommunityFix_OpenCertificateDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开 Hosts 文件夹 的本地化字符串。
        /// </summary>
        public static string CommunityFix_OpenHostsDir {
            get {
                return ResourceManager.GetString("CommunityFix_OpenHostsDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加速日志 的本地化字符串。
        /// </summary>
        public static string CommunityFix_ProxyLog {
            get {
                return ResourceManager.GetString("CommunityFix_ProxyLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 代理设置 的本地化字符串。
        /// </summary>
        public static string CommunityFix_ProxySettings {
            get {
                return ResourceManager.GetString("CommunityFix_ProxySettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 读取或还原文件时失败，因被其他进程占用，可能是其他不兼容的网络加速程序，请找到占用的进程将其关闭 的本地化字符串。
        /// </summary>
        public static string CommunityFix_ReadHosts_IOException {
            get {
                return ResourceManager.GetString("CommunityFix_ReadHosts_IOException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重置 Hosts 文件 的本地化字符串。
        /// </summary>
        public static string CommunityFix_ResetHostsFile {
            get {
                return ResourceManager.GetString("CommunityFix_ResetHostsFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重置 Hosts 文件失败，错误：{0} 的本地化字符串。
        /// </summary>
        public static string CommunityFix_ResetHostsFileCatchTip_ {
            get {
                return ResourceManager.GetString("CommunityFix_ResetHostsFileCatchTip_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重置 Hosts 文件成功 的本地化字符串。
        /// </summary>
        public static string CommunityFix_ResetHostsFileOk {
            get {
                return ResourceManager.GetString("CommunityFix_ResetHostsFileOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重置 Hosts 文件将删除所有数据并还原当前操作系统默认值，建议先编辑 Hosts 文件查看是否有需要的数据先进行备份后再执行此操作，是否确认重置？ 的本地化字符串。
        /// </summary>
        public static string CommunityFix_ResetHostsFileTip {
            get {
                return ResourceManager.GetString("CommunityFix_ResetHostsFileTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加速服务 的本地化字符串。
        /// </summary>
        public static string CommunityFix_Services {
            get {
                return ResourceManager.GetString("CommunityFix_Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 安装证书 的本地化字符串。
        /// </summary>
        public static string CommunityFix_SetupCertificate {
            get {
                return ResourceManager.GetString("CommunityFix_SetupCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 安装 CA 证书失败 的本地化字符串。
        /// </summary>
        public static string CommunityFix_SetupCertificate_Fail {
            get {
                return ResourceManager.GetString("CommunityFix_SetupCertificate_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 安装 CA 证书成功 的本地化字符串。
        /// </summary>
        public static string CommunityFix_SetupCertificate_Success {
            get {
                return ResourceManager.GetString("CommunityFix_SetupCertificate_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在启动加速... 的本地化字符串。
        /// </summary>
        public static string CommunityFix_Starting {
            get {
                return ResourceManager.GetString("CommunityFix_Starting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 一键加速 的本地化字符串。
        /// </summary>
        public static string CommunityFix_StartProxy {
            get {
                return ResourceManager.GetString("CommunityFix_StartProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加速服务启动失败，{0} 端口被占用。请关掉占用 {0} 端口的程序或者尝试使用系统代理模式 的本地化字符串。
        /// </summary>
        public static string CommunityFix_StartProxyFaild443_ {
            get {
                return ResourceManager.GetString("CommunityFix_StartProxyFaild443_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加速服务启动失败，{0} 端口被 {1}({2}) 占用。请关掉占用 {0} 端口的程序或者尝试使用系统代理模式 的本地化字符串。
        /// </summary>
        public static string CommunityFix_StartProxyFaild443___ {
            get {
                return ResourceManager.GetString("CommunityFix_StartProxyFaild443___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加速已启动成功 的本地化字符串。
        /// </summary>
        public static string CommunityFix_StartProxySuccess {
            get {
                return ResourceManager.GetString("CommunityFix_StartProxySuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停止加速 的本地化字符串。
        /// </summary>
        public static string CommunityFix_StopProxy {
            get {
                return ResourceManager.GetString("CommunityFix_StopProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 网络加速子进程文件不存在 的本地化字符串。
        /// </summary>
        public static string CommunityFix_SubProcessFileNotExist {
            get {
                return ResourceManager.GetString("CommunityFix_SubProcessFileNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定 的本地化字符串。
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 联系我们 的本地化字符串。
        /// </summary>
        public static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 继续 的本地化字符串。
        /// </summary>
        public static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 复制 的本地化字符串。
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已复制到剪贴板 的本地化字符串。
        /// </summary>
        public static string CopyToClipboard {
            get {
                return ResourceManager.GetString("CopyToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建证书失败 的本地化字符串。
        /// </summary>
        public static string CreateCertificateFaild {
            get {
                return ResourceManager.GetString("CreateCertificateFaild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择或拖拽文件到此 的本地化字符串。
        /// </summary>
        public static string CustomFilePicker_Tip {
            get {
                return ResourceManager.GetString("CustomFilePicker_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 剪切 的本地化字符串。
        /// </summary>
        public static string Cut {
            get {
                return ResourceManager.GetString("Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在此输入控制台指令 的本地化字符串。
        /// </summary>
        public static string Debug_InstructionPlaceholder {
            get {
                return ResourceManager.GetString("Debug_InstructionPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 默认 的本地化字符串。
        /// </summary>
        public static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开发商 的本地化字符串。
        /// </summary>
        public static string Developer {
            get {
                return ResourceManager.GetString("Developer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件夹路径 的本地化字符串。
        /// </summary>
        public static string DirPath {
            get {
                return ResourceManager.GetString("DirPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 禁用 的本地化字符串。
        /// </summary>
        public static string Disable {
            get {
                return ResourceManager.GetString("Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已禁用 的本地化字符串。
        /// </summary>
        public static string Disabled {
            get {
                return ResourceManager.GetString("Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下载 的本地化字符串。
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下行流量 的本地化字符串。
        /// </summary>
        public static string DownloadFlow {
            get {
                return ResourceManager.GetString("DownloadFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑 的本地化字符串。
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 邮箱 的本地化字符串。
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启用 的本地化字符串。
        /// </summary>
        public static string Enable {
            get {
                return ResourceManager.GetString("Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已启用 的本地化字符串。
        /// </summary>
        public static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加密 的本地化字符串。
        /// </summary>
        public static string Encrypt {
            get {
                return ResourceManager.GetString("Encrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误 的本地化字符串。
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不能在临时文件夹中运行此程序，请将所有文件复制或解压到其他路径后再启动程序 的本地化字符串。
        /// </summary>
        public static string Error_BaseDir_StartsWith_Temp {
            get {
                return ResourceManager.GetString("Error_BaseDir_StartsWith_Temp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此应用程序仅兼容 Windows 11 与 Windows 10 版本 1809（OS 内部版本 17763）或更高版本 的本地化字符串。
        /// </summary>
        public static string Error_IncompatibleOS {
            get {
                return ResourceManager.GetString("Error_IncompatibleOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发生了一些错误，无法打开此页面 的本地化字符串。
        /// </summary>
        public static string Error_PageFault {
            get {
                return ResourceManager.GetString("Error_PageFault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退出 的本地化字符串。
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出 的本地化字符串。
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出令牌 的本地化字符串。
        /// </summary>
        public static string ExportAuth {
            get {
                return ResourceManager.GetString("ExportAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 疑难解答 的本地化字符串。
        /// </summary>
        public static string FAQ {
            get {
                return ResourceManager.GetString("FAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件属性为只读，修改失败，请按网页指南操作 {0} 的本地化字符串。
        /// </summary>
        public static string FileAttributeIsReadOnlyModifyFailSeeWebPage_ {
            get {
                return ResourceManager.GetString("FileAttributeIsReadOnlyModifyFailSeeWebPage_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件属性为只读，修改失败，你可以尝试先备份该文件后删除再重试一遍 的本地化字符串。
        /// </summary>
        public static string FileAttributeIsReadOnlyModifyFailTryBakDelAgain {
            get {
                return ResourceManager.GetString("FileAttributeIsReadOnlyModifyFailTryBakDelAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件路径 的本地化字符串。
        /// </summary>
        public static string FilePath {
            get {
                return ResourceManager.GetString("FilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件大小 的本地化字符串。
        /// </summary>
        public static string FileSize {
            get {
                return ResourceManager.GetString("FileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件大小过大 的本地化字符串。
        /// </summary>
        public static string FileSizeTooLarge {
            get {
                return ResourceManager.GetString("FileSizeTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件访问被拒绝，没有权限 的本地化字符串。
        /// </summary>
        public static string FileUnauthorized {
            get {
                return ResourceManager.GetString("FileUnauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 筛选 的本地化字符串。
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修复网络完成 的本地化字符串。
        /// </summary>
        public static string FixNetworkComplete {
            get {
                return ResourceManager.GetString("FixNetworkComplete", resourceCulture);
            }
        }
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        /// <summary>
        ///   查找类似 库存游戏 的本地化字符串。
        /// </summary>
        public static string GameList {
            get {
                return ResourceManager.GetString("GameList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在加载... 的本地化字符串。
        /// </summary>
        public static string GameList_IsLoading {
            get {
                return ResourceManager.GetString("GameList_IsLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 仅显示支持 Steam 云存档的游戏 的本地化字符串。
        /// </summary>
        public static string GameList_OnlyCloudArchive {
            get {
                return ResourceManager.GetString("GameList_OnlyCloudArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 仅显示已安装的游戏 的本地化字符串。
        /// </summary>
        public static string GameList_OnlyInstalled {
            get {
                return ResourceManager.GetString("GameList_OnlyInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Steam 游戏已下载完成
        ///系统将在 {0} 秒后「{1}」。 的本地化字符串。
        /// <summary>
        ///   查找类似 Google 令牌 的本地化字符串。
        /// </summary>
        public static string Google {
            get {
                return ResourceManager.GetString("Google", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 帮助 的本地化字符串。
        /// </summary>
        public static string Helper {
            get {
                return ResourceManager.GetString("Helper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 读取 Hosts 成功 的本地化字符串。
        /// </summary>
        public static string Hosts_ReadSuccess {
            get {
                return ResourceManager.GetString("Hosts_ReadSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 写入 Hosts 成功 的本地化字符串。
        /// </summary>
        public static string Hosts_UpdateSuccess {
            get {
                return ResourceManager.GetString("Hosts_UpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 写入 Hosts 时发生错误 的本地化字符串。
        /// </summary>
        public static string Hosts_WirteError {
            get {
                return ResourceManager.GetString("Hosts_WirteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图标 的本地化字符串。
        /// </summary>
        public static string Icon {
            get {
                return ResourceManager.GetString("Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导入 的本地化字符串。
        /// </summary>
        public static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 信息 的本地化字符串。
        /// </summary>
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加载代理服务数据耗时：{0}ms，IsSuccess：{1}，Code：{2}，Count：{3} 的本地化字符串。
        /// </summary>
        public static string Info_LoadingAgentTakesTime____ {
            get {
                return ResourceManager.GetString("Info_LoadingAgentTakesTime____", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已安装 的本地化字符串。
        /// </summary>
        public static string Installed {
            get {
                return ResourceManager.GetString("Installed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前已是最新版本 的本地化字符串。
        /// </summary>
        public static string IsExistUpdateFalse {
            get {
                return ResourceManager.GetString("IsExistUpdateFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加入我们 的本地化字符串。
        /// </summary>
        public static string JoinUs {
            get {
                return ResourceManager.GetString("JoinUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动 的本地化字符串。
        /// </summary>
        public static string Launch {
            get {
                return ResourceManager.GetString("Launch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 库 的本地化字符串。
        /// </summary>
        public static string Library {
            get {
                return ResourceManager.GetString("Library", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 链接 的本地化字符串。
        /// </summary>
        public static string Link {
            get {
                return ResourceManager.GetString("Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Linux 需要提供系统 root 密码才能正常使用该功能 的本地化字符串。
        /// </summary>
        public static string LinuxSudoTips {
            get {
                return ResourceManager.GetString("LinuxSudoTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加载中… 的本地化字符串。
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 本地令牌 的本地化字符串。
        /// </summary>
        public static string LocalAuth {
            get {
                return ResourceManager.GetString("LocalAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定要永久删除此令牌吗，这只是删除令牌文件数据，并不会解绑你的账号和令牌，
        ///如果需要解绑令牌请到 https://store.steampowered.com/twofactor/manage 解绑后在删除。 的本地化字符串。
        /// <summary>
        ///   查找类似 需要解密才能继续 的本地化字符串。
        /// </summary>
        public static string LocalAuth_PasswordRequired {
            get {
                return ResourceManager.GetString("LocalAuth_PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入密码 的本地化字符串。
        /// </summary>
        public static string LocalAuth_PasswordRequired1 {
            get {
                return ResourceManager.GetString("LocalAuth_PasswordRequired1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 令牌加密 的本地化字符串。
        /// </summary>
        public static string LocalAuth_ProtectionAuth {
            get {
                return ResourceManager.GetString("LocalAuth_ProtectionAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自定义密码 的本地化字符串。
        /// </summary>
        public static string LocalAuth_ProtectionAuth_Password {
            get {
                return ResourceManager.GetString("LocalAuth_ProtectionAuth_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码错误 的本地化字符串。
        /// </summary>
        public static string LocalAuth_ProtectionAuth_PasswordError {
            get {
                return ResourceManager.GetString("LocalAuth_ProtectionAuth_PasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入正确的密码 的本地化字符串。
        /// </summary>
        public static string LocalAuth_ProtectionAuth_PasswordErrorTip {
            get {
                return ResourceManager.GetString("LocalAuth_ProtectionAuth_PasswordErrorTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 还差一步，请输入发送到您手机的短信验证代码，并点击继续按钮。
        ///请记住你的恢复代码，这很重要！ 的本地化字符串。
        /// <summary>
        ///   查找类似 登 录 的本地化字符串。
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        
        /// <summary>
        ///   查找类似 注销登录 的本地化字符串。
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请在弹出的控制台窗口中输入密码或者手动执行 的本地化字符串。
        /// </summary>
        public static string MacSudoPasswordTips {
            get {
                return ResourceManager.GetString("MacSudoPasswordTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请在弹出的控制台窗口输入系统密码以安装信任证书，信任完成后点击确定按钮继续 的本地化字符串。
        /// </summary>
        public static string MacTrustRootCertificateTips {
            get {
                return ResourceManager.GetString("MacTrustRootCertificateTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最大化 的本地化字符串。
        /// </summary>
        public static string Maximize {
            get {
                return ResourceManager.GetString("Maximize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 媒体 的本地化字符串。
        /// </summary>
        public static string Media {
            get {
                return ResourceManager.GetString("Media", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Microsoft 令牌 的本地化字符串。
        /// </summary>
        public static string Microsoft {
            get {
                return ResourceManager.GetString("Microsoft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最小化 的本地化字符串。
        /// </summary>
        public static string Minimize {
            get {
                return ResourceManager.GetString("Minimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您确认要取消所有交易报价吗
        ///您将拒绝列表内全部的报价请求。
        ///这将从以下列表中移除所有交易信息
        ///您可以在 Steam 库存查看交易报价记录。 的本地化字符串。
        /// <summary>
        ///   查找类似 您确认需要取消交易报价吗
        ///这将从以下列表中移除此条确认信息
        ///您可以在 Steam 库存查看交易报价记录。 的本地化字符串。
        /// <summary>
        ///   查找类似 您确认要通过所有交易报价吗
        ///您将同意列表内全部的报价请求。
        ///交易一经确认无法撤销，请谨慎选择。 的本地化字符串。
        /// <summary>
        ///   查找类似 {0}
        ///{1}
        ///{2}
        ///
        ///{3}
        ///如果您没有创建此交易，请立即取消该交易。您的账户或电脑可能已遭盗用。 的本地化字符串。
        /// <summary>
        ///   查找类似 修改 的本地化字符串。
        /// </summary>
        public static string Modify {
            get {
                return ResourceManager.GetString("Modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更多操作 的本地化字符串。
        /// </summary>
        public static string More {
            get {
                return ResourceManager.GetString("More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更多信息 的本地化字符串。
        /// </summary>
        public static string MoreInfo {
            get {
                return ResourceManager.GetString("MoreInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 我的 的本地化字符串。
        /// </summary>
        public static string My {
            get {
                return ResourceManager.GetString("My", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 名称 的本地化字符串。
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新功能正在开发中... 的本地化字符串。
        /// </summary>
        public static string NewFeatureDevelopment {
            get {
                return ResourceManager.GetString("NewFeatureDevelopment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 昵称 的本地化字符串。
        /// </summary>
        public static string NickName {
            get {
                return ResourceManager.GetString("NickName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当有新公告时的提示通知 的本地化字符串。
        /// </summary>
        public static string NotificationChannelType_Description_Announcement {
            get {
                return ResourceManager.GetString("NotificationChannelType_Description_Announcement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当开启前台服务时的通知 的本地化字符串。
        /// </summary>
        public static string NotificationChannelType_Description_ForegroundService {
            get {
                return ResourceManager.GetString("NotificationChannelType_Description_ForegroundService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当有提示消息时的通知 的本地化字符串。
        /// </summary>
        public static string NotificationChannelType_Description_Message {
            get {
                return ResourceManager.GetString("NotificationChannelType_Description_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当有新版本可用时的提示通知与下载新版本时的进度通知 的本地化字符串。
        /// </summary>
        public static string NotificationChannelType_Description_NewVersion {
            get {
                return ResourceManager.GetString("NotificationChannelType_Description_NewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 我的消息 的本地化字符串。
        /// </summary>
        public static string NotificationChannelType_Name_Announcement {
            get {
                return ResourceManager.GetString("NotificationChannelType_Name_Announcement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 前台服务通知 的本地化字符串。
        /// </summary>
        public static string NotificationChannelType_Name_ForegroundService {
            get {
                return ResourceManager.GetString("NotificationChannelType_Name_ForegroundService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 消息通知 的本地化字符串。
        /// </summary>
        public static string NotificationChannelType_Name_Message {
            get {
                return ResourceManager.GetString("NotificationChannelType_Name_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新版本通知 的本地化字符串。
        /// </summary>
        public static string NotificationChannelType_Name_NewVersion {
            get {
                return ResourceManager.GetString("NotificationChannelType_Name_NewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关 的本地化字符串。
        /// </summary>
        public static string Off {
            get {
                return ResourceManager.GetString("Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开 的本地化字符串。
        /// </summary>
        public static string On {
            get {
                return ResourceManager.GetString("On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开主面板 的本地化字符串。
        /// </summary>
        public static string OpenMainWindow {
            get {
                return ResourceManager.GetString("OpenMainWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开官网 的本地化字符串。
        /// </summary>
        public static string OpenOfficialWebsite {
            get {
                return ResourceManager.GetString("OpenOfficialWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开放源代码库 的本地化字符串。
        /// </summary>
        public static string OpenSourceLibrary {
            get {
                return ResourceManager.GetString("OpenSourceLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作 Hosts 错误 {0} 的本地化字符串。
        /// </summary>
        public static string OperationHostsError_ {
            get {
                return ResourceManager.GetString("OperationHostsError_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 粘贴 的本地化字符串。
        /// </summary>
        public static string Paste {
            get {
                return ResourceManager.GetString("Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择图片缩放方式 的本地化字符串。
        /// </summary>
        public static string PictureZoom {
            get {
                return ResourceManager.GetString("PictureZoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 作者：{0} 的本地化字符串。
        /// </summary>
        public static string Plugin_Author {
            get {
                return ResourceManager.GetString("Plugin_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        public static string Plugin_Delete {
            get {
                return ResourceManager.GetString("Plugin_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否要删除 {0} 插件 的本地化字符串。
        /// </summary>
        public static string Plugin_DeleteComfirm {
            get {
                return ResourceManager.GetString("Plugin_DeleteComfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 插件删除成功 的本地化字符串。
        /// </summary>
        public static string Plugin_DeleteSuccess {
            get {
                return ResourceManager.GetString("Plugin_DeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 找不到文件 的本地化字符串。
        /// </summary>
        public static string Plugin_FileError {
            get {
                return ResourceManager.GetString("Plugin_FileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 存在非法字符 的本地化字符串。
        /// </summary>
        public static string Plugin_IllegalAuthor {
            get {
                return ResourceManager.GetString("Plugin_IllegalAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已安装插件 的本地化字符串。
        /// </summary>
        public static string Plugin_InstalledPlugins {
            get {
                return ResourceManager.GetString("Plugin_InstalledPlugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 管理所有已安装插件 的本地化字符串。
        /// </summary>
        public static string Plugin_ManageAllInstalledPlugins {
            get {
                return ResourceManager.GetString("Plugin_ManageAllInstalledPlugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 需要先禁用该插件 的本地化字符串。
        /// </summary>
        public static string Plugin_NeedDisable {
            get {
                return ResourceManager.GetString("Plugin_NeedDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}  官方 的本地化字符串。
        /// </summary>
        public static string Plugin_OfficialAuthor_ {
            get {
                return ResourceManager.GetString("Plugin_OfficialAuthor_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 仅加载官方插件 的本地化字符串。
        /// </summary>
        public static string Plugin_OnlyLoadOfficePlugins {
            get {
                return ResourceManager.GetString("Plugin_OnlyLoadOfficePlugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开插件 AppData 文件夹 的本地化字符串。
        /// </summary>
        public static string Plugin_OpenAppDataFolder {
            get {
                return ResourceManager.GetString("Plugin_OpenAppDataFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开插件缓存文件夹 的本地化字符串。
        /// </summary>
        public static string Plugin_OpenCacheFolder {
            get {
                return ResourceManager.GetString("Plugin_OpenCacheFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开插件文件夹 的本地化字符串。
        /// </summary>
        public static string Plugin_OpenFolder {
            get {
                return ResourceManager.GetString("Plugin_OpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 安全模式 的本地化字符串。
        /// </summary>
        public static string Plugin_SafeMode {
            get {
                return ResourceManager.GetString("Plugin_SafeMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未知 的本地化字符串。
        /// </summary>
        public static string Plugin_UnknownAuthor {
            get {
                return ResourceManager.GetString("Plugin_UnknownAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 版本号： 的本地化字符串。
        /// </summary>
        public static string Plugin_Version {
            get {
                return ResourceManager.GetString("Plugin_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 预览图片 的本地化字符串。
        /// </summary>
        public static string PreviewPictures {
            get {
                return ResourceManager.GetString("PreviewPictures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DNS 驱动拦截模式 的本地化字符串。
        /// </summary>
        public static string ProxyMode_DNSIntercept {
            get {
                return ResourceManager.GetString("ProxyMode_DNSIntercept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hosts 代理模式 的本地化字符串。
        /// </summary>
        public static string ProxyMode_Hosts {
            get {
                return ResourceManager.GetString("ProxyMode_Hosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 仅代理模式 的本地化字符串。
        /// </summary>
        public static string ProxyMode_ProxyOnly {
            get {
                return ResourceManager.GetString("ProxyMode_ProxyOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 VPN 代理模式 的本地化字符串。
        /// </summary>
        public static string ProxyMode_VPN {
            get {
                return ResourceManager.GetString("ProxyMode_VPN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发行商 的本地化字符串。
        /// </summary>
        public static string Publisher {
            get {
                return ResourceManager.GetString("Publisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 刷新 的本地化字符串。
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不再提醒 的本地化字符串。
        /// </summary>
        public static string RememberChooseNotToAskAgain {
            get {
                return ResourceManager.GetString("RememberChooseNotToAskAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重置 的本地化字符串。
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 还原 的本地化字符串。
        /// </summary>
        public static string Restore {
            get {
                return ResourceManager.GetString("Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收起 的本地化字符串。
        /// </summary>
        public static string Retract {
            get {
                return ResourceManager.GetString("Retract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重试 的本地化字符串。
        /// </summary>
        public static string Retry {
            get {
                return ResourceManager.GetString("Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存 的本地化字符串。
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 存档 的本地化字符串。
        /// </summary>
        public static string SaveFile {
            get {
                return ResourceManager.GetString("SaveFile", resourceCulture);
            }
        }
        
        
        /// <summary>
        ///   查找类似 脚本工坊 的本地化字符串。
        /// </summary>
        public static string ScriptStore {
            get {
                return ResourceManager.GetString("ScriptStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 搜索… 的本地化字符串。
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全选 的本地化字符串。
        /// </summary>
        public static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择文件 的本地化字符串。
        /// </summary>
        public static string SelectFile {
            get {
                return ResourceManager.GetString("SelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择一张照片 的本地化字符串。
        /// </summary>
        public static string SelectPicture {
            get {
                return ResourceManager.GetString("SelectPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启用开机自启动失败，原因：{0} 的本地化字符串。
        /// </summary>
        public static string SetBootAutoStartTrueFail_ {
            get {
                return ResourceManager.GetString("SetBootAutoStartTrueFail_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置 的本地化字符串。
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字体 的本地化字符串。
        /// </summary>
        public static string Settings_Fonts {
            get {
                return ResourceManager.GetString("Settings_Fonts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 通用设置 的本地化字符串。
        /// </summary>
        public static string Settings_General {
            get {
                return ResourceManager.GetString("Settings_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AppData 数据 的本地化字符串。
        /// </summary>
        public static string Settings_General_AppData {
            get {
                return ResourceManager.GetString("Settings_General_AppData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开 {0} 文件夹 的本地化字符串。
        /// </summary>
        public static string Settings_General_BrowseCustomFolder {
            get {
                return ResourceManager.GetString("Settings_General_BrowseCustomFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cache 数据 的本地化字符串。
        /// </summary>
        public static string Settings_General_CacheData {
            get {
                return ResourceManager.GetString("Settings_General_CacheData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 缓存文件已占用 {0} 的本地化字符串。
        /// </summary>
        public static string Settings_General_CacheSize {
            get {
                return ResourceManager.GetString("Settings_General_CacheSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 计算中… 的本地化字符串。
        /// </summary>
        public static string Settings_General_Calcing {
            get {
                return ResourceManager.GetString("Settings_General_Calcing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启用托盘图标 的本地化字符串。
        /// </summary>
        public static string Settings_General_EnableTrayIcon {
            get {
                return ResourceManager.GetString("Settings_General_EnableTrayIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 禁用此选项时关闭主窗口将直接退出程序 的本地化字符串。
        /// </summary>
        public static string Settings_General_EnableTrayIcon_Tip {
            get {
                return ResourceManager.GetString("Settings_General_EnableTrayIcon_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Logs 数据 的本地化字符串。
        /// </summary>
        public static string Settings_General_LogsData {
            get {
                return ResourceManager.GetString("Settings_General_LogsData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日志文件已占用 {0} 的本地化字符串。
        /// </summary>
        public static string Settings_General_LogSize {
            get {
                return ResourceManager.GetString("Settings_General_LogSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动时最小化到托盘 的本地化字符串。
        /// </summary>
        public static string Settings_General_RuningMinimize {
            get {
                return ResourceManager.GetString("Settings_General_RuningMinimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开机自启动 的本地化字符串。
        /// </summary>
        public static string Settings_General_StartAutoRun {
            get {
                return ResourceManager.GetString("Settings_General_StartAutoRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 存储空间 的本地化字符串。
        /// </summary>
        public static string Settings_General_StorageSpace {
            get {
                return ResourceManager.GetString("Settings_General_StorageSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用 GPU 渲染界面（硬件加速） 的本地化字符串。
        /// </summary>
        public static string Settings_General_UseGPURendering {
            get {
                return ResourceManager.GetString("Settings_General_UseGPURendering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无效的配置文件 的本地化字符串。
        /// </summary>
        public static string Settings_InvalidConfigurationFile {
            get {
                return ResourceManager.GetString("Settings_InvalidConfigurationFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 语言 的本地化字符串。
        /// </summary>
        public static string Settings_Language {
            get {
                return ResourceManager.GetString("Settings_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 插件设置 的本地化字符串。
        /// </summary>
        public static string Settings_Plugin {
            get {
                return ResourceManager.GetString("Settings_Plugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自定义代理 DNS 的本地化字符串。
        /// </summary>
        public static string Settings_Proxy_CustomDNS {
            get {
                return ResourceManager.GetString("Settings_Proxy_CustomDNS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 地址 的本地化字符串。
        /// </summary>
        public static string Settings_Proxy_IPAddress {
            get {
                return ResourceManager.GetString("Settings_Proxy_IPAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码 的本地化字符串。
        /// </summary>
        public static string Settings_Proxy_Password {
            get {
                return ResourceManager.GetString("Settings_Proxy_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 端口 的本地化字符串。
        /// </summary>
        public static string Settings_Proxy_Port {
            get {
                return ResourceManager.GetString("Settings_Proxy_Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 代理类型 的本地化字符串。
        /// </summary>
        public static string Settings_Proxy_ProxyType {
            get {
                return ResourceManager.GetString("Settings_Proxy_ProxyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 二级代理 的本地化字符串。
        /// </summary>
        public static string Settings_Proxy_TwoLevelAgent {
            get {
                return ResourceManager.GetString("Settings_Proxy_TwoLevelAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名 的本地化字符串。
        /// </summary>
        public static string Settings_Proxy_UserName {
            get {
                return ResourceManager.GetString("Settings_Proxy_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 *需重启软件后生效 的本地化字符串。
        /// </summary>
        public static string Settings_RestartEffective {
            get {
                return ResourceManager.GetString("Settings_RestartEffective", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统启动时程序自动运行 的本地化字符串。
        /// </summary>
        public static string Settings_StartupAutoRun {
            get {
                return ResourceManager.GetString("Settings_StartupAutoRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置后程序启动时不再主动显示主窗口 的本地化字符串。
        /// </summary>
        public static string Settings_StartupNoShowMainWindow {
            get {
                return ResourceManager.GetString("Settings_StartupNoShowMainWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主题 的本地化字符串。
        /// </summary>
        public static string Settings_Theme {
            get {
                return ResourceManager.GetString("Settings_Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主题色 的本地化字符串。
        /// </summary>
        public static string Settings_ThemeAccent {
            get {
                return ResourceManager.GetString("Settings_ThemeAccent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 界面设置 的本地化字符串。
        /// </summary>
        public static string Settings_UI {
            get {
                return ResourceManager.GetString("Settings_UI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置程序中显示的强调色 的本地化字符串。
        /// </summary>
        public static string Settings_UI_AccentColor {
            get {
                return ResourceManager.GetString("Settings_UI_AccentColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 背景图片不透明度 的本地化字符串。
        /// </summary>
        public static string Settings_UI_BackgroundImageOpacity {
            get {
                return ResourceManager.GetString("Settings_UI_BackgroundImageOpacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 背景不透明度 的本地化字符串。
        /// </summary>
        public static string Settings_UI_BackgroundOpacity {
            get {
                return ResourceManager.GetString("Settings_UI_BackgroundOpacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自定义 的本地化字符串。
        /// </summary>
        public static string Settings_UI_Custom {
            get {
                return ResourceManager.GetString("Settings_UI_Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自定义背景图片 的本地化字符串。
        /// </summary>
        public static string Settings_UI_CustomBackgroundImage {
            get {
                return ResourceManager.GetString("Settings_UI_CustomBackgroundImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择的图片格式不正确 的本地化字符串。
        /// </summary>
        public static string Settings_UI_CustomBackgroundImage_Error {
            get {
                return ResourceManager.GetString("Settings_UI_CustomBackgroundImage_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自定义颜色 的本地化字符串。
        /// </summary>
        public static string Settings_UI_CustomColor {
            get {
                return ResourceManager.GetString("Settings_UI_CustomColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 深色 的本地化字符串。
        /// </summary>
        public static string Settings_UI_Dark {
            get {
                return ResourceManager.GetString("Settings_UI_Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置程序首选的字体 的本地化字符串。
        /// </summary>
        public static string Settings_UI_DefaultFonts {
            get {
                return ResourceManager.GetString("Settings_UI_DefaultFonts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置程序首选的显示语言 的本地化字符串。
        /// </summary>
        public static string Settings_UI_DefaultLanguage {
            get {
                return ResourceManager.GetString("Settings_UI_DefaultLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用动态桌面背景 的本地化字符串。
        /// </summary>
        public static string Settings_UI_EnableDesktopBackground {
            get {
                return ResourceManager.GetString("Settings_UI_EnableDesktopBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不支持在背景透明材质为 {0} 时启用此功能 的本地化字符串。
        /// </summary>
        public static string Settings_UI_EnableDesktopBackground_Error_ {
            get {
                return ResourceManager.GetString("Settings_UI_EnableDesktopBackground_Error_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 高对比度 的本地化字符串。
        /// </summary>
        public static string Settings_UI_HighContrast {
            get {
                return ResourceManager.GetString("Settings_UI_HighContrast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 浅色 的本地化字符串。
        /// </summary>
        public static string Settings_UI_Light {
            get {
                return ResourceManager.GetString("Settings_UI_Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 预览颜色 的本地化字符串。
        /// </summary>
        public static string Settings_UI_PreviewColor {
            get {
                return ResourceManager.GetString("Settings_UI_PreviewColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择图片 的本地化字符串。
        /// </summary>
        public static string Settings_UI_SelectImage {
            get {
                return ResourceManager.GetString("Settings_UI_SelectImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动时默认打开页面 的本地化字符串。
        /// </summary>
        public static string Settings_UI_StartDefaultPage {
            get {
                return ResourceManager.GetString("Settings_UI_StartDefaultPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 跟随系统 的本地化字符串。
        /// </summary>
        public static string Settings_UI_SystemDefault {
            get {
                return ResourceManager.GetString("Settings_UI_SystemDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置程序的主题风格 的本地化字符串。
        /// </summary>
        public static string Settings_UI_ThemeStyle {
            get {
                return ResourceManager.GetString("Settings_UI_ThemeStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置窗口背景透明效果和透明材质 的本地化字符串。
        /// </summary>
        public static string Settings_UI_WindowBackgroundStyle {
            get {
                return ResourceManager.GetString("Settings_UI_WindowBackgroundStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 窗口背景透明材质 的本地化字符串。
        /// </summary>
        public static string Settings_UI_WindowTransparencyMaterial {
            get {
                return ResourceManager.GetString("Settings_UI_WindowTransparencyMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置已修改，需重启软件后生效 的本地化字符串。
        /// </summary>
        public static string SettingsModifiedRestartThisSoft {
            get {
                return ResourceManager.GetString("SettingsModifiedRestartThisSoft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 签到 的本地化字符串。
        /// </summary>
        public static string Sign {
            get {
                return ResourceManager.GetString("Sign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已签到 的本地化字符串。
        /// </summary>
        public static string Signed {
            get {
                return ResourceManager.GetString("Signed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退出登录 的本地化字符串。
        /// </summary>
        public static string SignOut {
            get {
                return ResourceManager.GetString("SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 赞助我们 的本地化字符串。
        /// </summary>
        public static string SponsorUs {
            get {
                return ResourceManager.GetString("SponsorUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已游玩 {0} 小时 
        ///{1} 张剩余卡牌掉落
        ///卡牌均价 ￥{2} 的本地化字符串。
        /// <summary>
        ///   查找类似 登录的账号与当前 Steam 客户端账号不一致，可能会导致挂卡出现问题。
        ///请注销切换登录账号与 Steam 客户端账号一致，
        ///或切换 Steam 客户端登录账号与挂卡账号一致！ 的本地化字符串。
        
        /// <summary>
        ///   查找类似 停止 的本地化字符串。
        /// </summary>
        public static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        
        /// <summary>
        ///   查找类似 置顶 的本地化字符串。
        /// </summary>
        public static string Top {
            get {
                return ResourceManager.GetString("Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入系统密码继续或者复制命令手动执行 的本地化字符串。
        /// </summary>
        public static string UnixSudoPasswordTips {
            get {
                return ResourceManager.GetString("UnixSudoPasswordTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上移 的本地化字符串。
        /// </summary>
        public static string Up {
            get {
                return ResourceManager.GetString("Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上传 的本地化字符串。
        /// </summary>
        public static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上行流量 的本地化字符串。
        /// </summary>
        public static string UploadFlow {
            get {
                return ResourceManager.GetString("UploadFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户协议 的本地化字符串。
        /// </summary>
        public static string User_Agreement {
            get {
                return ResourceManager.GetString("User_Agreement", resourceCulture);
            }
        }
        
        
        
        /// <summary>
        ///   查找类似 隐私政策 的本地化字符串。
        /// </summary>
        public static string User_Privacy {
            get {
                return ResourceManager.GetString("User_Privacy", resourceCulture);
            }
        }
        
        
        
        
        /// <summary>
        ///   查找类似 确定要登录 Steam 新账户吗？
        ///此操作会结束正在运行的 Steam 跳转到新账号登录窗口。 的本地化字符串。
        /// <summary>
        ///   查找类似 个人资料 的本地化字符串。
        /// </summary>
        public static string UserProfile {
            get {
                return ResourceManager.GetString("UserProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 验证 的本地化字符串。
        /// </summary>
        public static string Verify {
            get {
                return ResourceManager.GetString("Verify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 警告 的本地化字符串。
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请勿频繁操作 的本地化字符串。
        /// </summary>
        public static string Warning_DoNotOperateFrequently {
            get {
                return ResourceManager.GetString("Warning_DoNotOperateFrequently", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请先停止加速 的本地化字符串。
        /// </summary>
        public static string Warning_PleaseStopAccelerate {
            get {
                return ResourceManager.GetString("Warning_PleaseStopAccelerate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主页 的本地化字符串。
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 工作目录 的本地化字符串。
        /// </summary>
        public static string WorkingDir {
            get {
                return ResourceManager.GetString("WorkingDir", resourceCulture);
            }
        }
        
    }
}
